
FROM node:22-alpine
WORKDIR /app
COPY ./package.json ./package.json
COPY ./public ./public
COPY ./src ./src
COPY ./index.html ./index.html
COPY ./postcss.config.js ./postcss.config.js
COPY ./.env ./.env
COPY ./tailwind.config.js ./tailwind.config.js
COPY vite.config.js ./vite.config.js
RUN npm install
EXPOSE 5173
CMD ["npm","run","dev"]