services:
  slackfrontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile.reactUI
    image: dsumanta/ecommerce:frontend
    ports:
      - "5173:5173"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - nodebackend
  nodebackend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.node
    image: dsumanta/ecommerce:backend
    ports:
      - "8080:8080"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
  db:
    volumes:
      - slack_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"
volumes:
  slack_db:
