services:
  slackfrontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile.reactUI
    ports:
      - "5173:5173"
    depends_on:
      - nodebackend
  nodebackend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.node
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    volumes:
      - slack_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"
volumes:
  slack_db:
