version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # MongoDB data persistence
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app  # Mount backend code for live updates
    networks:
      - app-network


  frontend:
    build:
      context: ./frontend/FrontEndaPart
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/FrontEndaPart:/app  # Mount frontend code for live updates
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local  # Persistent MongoDB data storage

networks:
  app-network:
    driver: bridge
