# FROM node:22-alpine
# WORKDIR /app
# COPY ./package.json ./package.json
# COPY ./index.js ./index.js
# COPY ./.env ./.env
# COPY ./Router ./Router
# COPY ./Model ./Model
# COPY ./Middleware ./Middleware
# COPY ./Helper ./Helper
# COPY ./Controller ./Controller
# COPY ./Config ./Config
# RUN npm install 
# EXPOSE 8080
# CMD ["npm","run","dev"]

FROM node:22-alpine
WORKDIR /app
COPY package.json .
RUN npm install
EXPOSE 8080
CMD ["npm", "run", "dev"]